# Generated by Django 5.1.6 on 2025-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamart', '0003_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
